# Data Versions Tests
#
# Prerequisites
# -------------
# - Execute auth.http first.
# - Valid access token.
# - API running on localhost:60004

@baseUrl = http://localhost:60004/data-versions
@token = PASTE_ACCESS_TOKEN
@resource = devices

############################################################
# Get resource version
#
# Expected:
# Status: 200
# Response:
# {
#   "version": "1"
# }
############################################################

GET {{baseUrl}}/{{resource}}
Authorization: Bearer {{token}}
